name: Building crdroid

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/crdroidandroid/android -b 13.0
  DEVICE: p3s
  DT_LINK: https://github.com/Exy2100-LOS/android_device_samsung_p3s
  DT_PATH: device/samsung/p3s
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
             git clone https://github.com/SA-17/rm_pkg p && cd p && bash setup.sh
             sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
             sudo chmod a+rx /usr/local/bin/repo
            
            
       - name: Sync recovery source and device tree
         run: |
              mkdir work
              cd work
              git clone 
              repo init https://github.com/crdroidandroid/android -b 13.0 --depth=1
              repo sync -c -j700 --force-sync --no-clone-bundle --no-tags
              git clone $DT_LINK --depth=1 --single-branch $DT_PATH
              ls

       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch lineage_p3s && mka p3s -j16
              zip crdroid.zip /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/*zip*
              ls
              
       - name: Save
         uses: actions/upload-artifact@v2
         with:
            name: recovery.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/p3s/*zip*
            retention-days: 31
          
       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name:  crdroid For p3s (Unofficial) 
          files: /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/p3s/*zip*



