name: Building crdroid

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/crdroidandroid/android -b 7.1
  DEVICE: goyave
  DT_LINK: https://github.com/pstglia/local_manifests
  DT_PATH: device/samsung/goyave
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
             git clone https://github.com/SA-17/rm_pkg p && cd p && bash setup.sh
             sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
             sudo chmod a+rx /usr/local/bin/repo
            
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1
             repo sync -c -j100 --force-sync --no-clone-bundle --no-tags
             git clone $DT_LINK $DT_PATH --depth=1            
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh && brunch $DEVICE
              zip crdroid.zip /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/*droid*
             
       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: crdroid.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/crdroid.zip
            retention-days: 5
