name: Building halium

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/crdroidandroid/android -b 13.0
  DEVICE: core33g
  DT_LINK: https://github.com/pstglia/android_device_samsung_core33g.git
  DT_PATH: device/samsung/core33g
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
             git clone https://github.com/SA-17/rm_pkg p && cd p && bash setup.sh
             sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
             sudo chmod a+rx /usr/local/bin/repo
            
            
       - name: Sync recovery source and device tree
         run: |
              mkdir work
              cd work
              git clone $DT_LINK --single-branch $DT_PATH --depth=1
              repo init -u https://github.com/Halium/android -b halium-7.1 --depth=1
              repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
              cd device/samsung/core33g
              ls

       - name: Build
         run: |
              cd work
              . build/envsetup.sh && breakfast core33g && mka systemimg
              zip crdroid.zip /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/*img*
              ls
              
       - name: Save
         uses: actions/upload-artifact@v2
         with:
            name: recovery.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/core33g/*img*
            retention-days: 31
          
       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name:  halium For core33g (system.img) boot.img will be released later (Unofficial) 
          files: /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/core33g/*img*



