name: Building halium

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/crdroidandroid/android -b 13.1
  DEVICE: universal2100-common
  DT_LINK: https://github.com/Exy2100-LOS/android_device_samsung_universal2100-common.git
  DT_PATH: device/samsung/universal2100-common
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
             git clone https://github.com/SA-17/rm_pkg p && cd p && bash setup.sh
             sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
             sudo chmod a+rx /usr/local/bin/repo
            
            
       - name: Sync recovery source and device tree
         run: |
              mkdir work
              cd work
              git clone $DT_LINK --single-branch $DT_PATH --depth=1
              repo init -u https://github.com/crdroidandroid/android -b 13.1 --depth=1
              repo sync -c -j5 --force-sync --no-clone-bundle --no-tags
              cd device/samsung/universal2100-common
              ls

       - name: Build
         run: |
              cd work
              . build/envsetup.sh && breakfast $DEVICE && make $DEVICE
              zip crdroid.zip /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/*zip*
              ls
              
       - name: Save
         uses: actions/upload-artifact@v2
         with:
            name: recovery.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/universal2100-common/*zip*
            retention-days: 31
          
       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name:  halium For universal2100-common (Unofficial) 
          files: /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/universal2100-common/*zip*



