name: Building lineage-15.1 

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/Halium/android -b halium-7.1 --depth=1 -b 7.1 
  DEVICE: core33g
  DT_LINK: https://github.com/Hasajapathirana/android_device_samsung_core33g
  DT_PATH: device/samsung/core33g
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
             git clone https://github.com/SA-17/rm_pkg p && cd p && bash setup.sh
             sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
             sudo chmod a+rx /usr/local/bin/repo
            
            
       - name: Sync recovery source and device tree
         run: |
              mkdir work
              cd work
              repo init -u https://github.com/LineageOS/android.git -b lineage-15.1 --depth=1
              repo sync -j16
              git clone --depth=1 -b lineageos-15.1 https://github.com/Hasajapathirana/android_device_samsung_goyavewifi.git device/samsung/goyavewifi
              git clone --depth=1 -b T113NU_COM_A_MAO_NO_BOLSO https://github.com/pstglia/linux.git kernel/samsung/core33g
              git clone --depth=1 -b lineageos-15.1 https://github.com/Hasajapathirana/android_vendor_samsung_goyavewifi.git vendor/samsung/goyavewifi              git clone --depth=1 https://github.com/gtel3g/android_device_samsung_scx30g-common.git device/samsung/scx30g-common -b lineage-15.1-gtel3g
              git clone --depth=1 https://github.com/gtel3g/android_vendor_samsung_scx30g-common.git vendor/samsung/scx30g-common -b lineage-15.1
              git clone --depth=1 https://github.com/LineageOS/android_external_stlport.git external/stlport -b lineage-15.1
              git clone --depth=1 https://github.com/gtel3g/android_device_samsung_sprd-common.git device/samsung/sprd-common -b lineage-15.1
              git clone --depth=1 https://github.com/gtel3g/android_device_samsung_scx35-common.git device/samsung/scx35-common -b lineage-15.1
              git clone --depth=1 https://github.com/gtel3g/android_hardware_sprd.git hardware/sprd -b lineage-15.1
              git clone --depth=1 https://github.com/LineageOS/android_packages_resources_devicesettings.git packages/resources/devicesettings -b lineage-15.1
       - name: Build
         run: |
              cd work
              source build/envsetup.sh && breakfast goyavewifi
              croot
              brunch goyavewifi
              ls
              
       - name: Save
         uses: actions/upload-artifact@v2
         with:
            name: system.zip
            path: |
             /home/runner/work/Recovery_builder/Recovery_builder/work/out/*lineage-15.1 *.zip
             /home/runner/work/Recovery_builder/Recovery_builder/work/out/recovery.img
            retention-days: 31
          




