name: Building OrangeFox Recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  DEVICE: p3s
  DT_LINK: https://github.com/Hasajapathirana/android_device_samsung_p3s-1
  DT_PATH: device/samsung/p3s
  TARGET: recoveryimage
  OT: twrp_
  
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-20.04
    

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: remove pkg and setting repo
         run: |
            sudo apt update && sudo apt install git
            git clone https://github.com/SA-17/rm_pkg pkg && cd pkg && bash setup.sh
            cd .. && sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential tar zip curl libstdc++6 git wget python3 gcc clang libssl-dev rsync flex curl  bison aria2
            sudo rm -rf /opt/*
            sudo apt update
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            sudo apt install zip
            git clone https://gitlab.com/OrangeFox/misc/scripts
            cd scripts
            sudo bash setup/android_build_env.sh
            
  
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             mkdir fox_12.1
             git clone https://gitlab.com/OrangeFox/sync.git
             cd sync
             ./orangefox_sync.sh --branch 12.1 --path /home/runner/work/Recovery_builder/Recovery_builder/work/fox_12.1/
             ls
             cd /home/runner/work/Recovery_builder/Recovery_builder/work/fox_12.1/
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             
             
       - name: Build
         run: |
              cd /home/runner/work/Recovery_builder/Recovery_builder/work/fox_12.1/
              sudo su
              source build/envsetup.sh
              lunch twrp_p3s-eng
              mka recoveryimage -j16
              cd /out/target/product/p3s/
              ls
            
            
              
       - name: Save
         uses: actions/upload-artifact@v2
         with:
            name: recovery.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/fox_12.1/out/target/product/p3s/*recovery*
            retention-days: 90
          
       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name:  OrangeFox Recovery For p3s (Unofficial) 
          files: /home/runner/work/Recovery_builder/Recovery_builder/fox_12.1/out/target/product/p3s/*recovery*
          retention-days: 90
