name: Building Pbrp recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/PitchBlackTWRP/manifest_pb.git -b android-12.1
  DEVICE: p3s
  DT_LINK: https://github.com/Hasajapathirana/android_device_samsung_p3s-1
  DT_PATH: device/samsung/p3s
  TARGET: recoveryimage
  OT: twrp_
  
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-20.04 

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: remove pkg and setting repo
         run: |
            sudo apt update && sudo apt install git
            git clone https://github.com/SA-17/rm_pkg pkg && cd pkg && bash setup.sh
            cd .. && sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential tar zip curl libstdc++6 git wget python3 gcc clang libssl-dev rsync flex curl  bison aria2
            sudo apt update
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local
            sudo apt install zip
  
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             sudo su
             repo init -u $MANIFEST --depth=1
             repo sync -c -j900 --force-sync --no-clone-bundle --no-tags
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch $OT$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka pbrp -j95
              zip pbrp.zip /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/*UNOFFICIAL*
              cd /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/
              ls

       - name: Save
         uses: actions/upload-artifact@v2
         with:
            name: recovery.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/pbrp.zip
            retention-days: 31


